### ISSUE TITLE
Sidebar height gets confused

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#100]
On Chrome/OS X the links on the bottom disappear after routes are received. They come back when you "jig" the window height a bit.

On Android (2.3) scrolling does not work at all.

Most likely culprit is the height: 100% stuff which is notorious for doing everything except the thing you want.

**Comment by sluukkonen** [comment]
Just FYI, the explicit height is there alongside with overflow:auto to add a visible scrollbar to the sidebar.

**Comment by teropa** [comment]
OK.. yeah, will have to see how to tweak it to make it work consistently across browsers.

**Comment by teropa** [comment]
Should be OK now.
