### ISSUE TITLE
Render index.html with i18n strings on the server

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#109]
This would mean index.html can't be a static file anymore.
Eliminates the weird moment when the UI is half blank, before we insert the language strings from the JS code.

Would also open up possibilities for piggybacking other stuff in the HTML, eliminating requests. For example, route data if it's a bookmark and we have those routes cached. (Though this is completely against the "static markup, dynamic data" idea which things like app cache is built on).

**Comment by sluukkonen** [comment]
We can also prefill the time & date forms.

**Comment by teropa** [comment]
The page is now a template, evaluated with handlebars. Closing this, the other optimization ideas can be implemented separately.
