### ISSUE TITLE
Scrolling is broken on Android 2.3 again

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#130]
Not sure what's happened now.

**Comment by sluukkonen** [comment]
Maybe fixed now?

**Comment by teropa** [comment]
nope :/

**Comment by sluukkonen** [comment]
Ok. I don't have an Android device for testing, but I this should be fairly straightforward to bisect.

**Comment by teropa** [comment]
Fixed by disabling position: fixed usage on small screens. Now it's all just in a normal div with position: static on <768.

**Comment by sluukkonen** [comment]
I think we have a lot of unncessary markup/CSS left form the times when we had the top bar. We should refactor it at some point and get rid of unnecessary cruft.
