### ISSUE TITLE
Limit zooming and panning to the relevant area

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#14]
Should include Helsinki, Vantaa, Espoo(Kauniainen), Kirkkonummi, Kerava, Sipoo

**Comment by joonas-sollasvaara** [comment]
This should apply to initial map centering too.
HSL doesn't operate where I live, so there's no point to center the map middle of nowhere.

**Comment by teropa** [comment]
Also to reverse geocoding: We don't need to waste our quota trying to locate coordinates that are outside the supported bounding box.

**Comment by teropa** [comment]
Everything else done except the panning restriction: It isn't supported by Google Maps API directly, and would have to be done by listening to drag events and preventing them from going outside bounds. I say this is not worth the effort right now.
