### ISSUE TITLE
ihanhyvareittiopas.fi is down

### ISSUE THREAD

**Issue by apaatsio** [reitti/reittiopas#161]
"Server not found."

This also says it's down: http://www.downforeveryoneorjustme.com/www.ihanhyvareittiopas.fi

```
nslookup ihanhyvareittiopas.fi
Server:     8.8.8.8
Address:    8.8.8.8#53

** server can't find ihanhyvareittiopas.fi: NXDOMAIN
```

**Comment by deanc** [comment]
Seems it's been down a long time. Too bad, I absolutely loved using this service!

**Comment by richrd** [comment]
Same here! Hopefully the author will fix it, but on the other hand who knows... Maybe one of us fans could re-host it. I could try it, especially if the author hasn't got time for it. Lets see.

**Comment by apaatsio** [comment]
Closing as stale.
