### ISSUE TITLE
Only show the current location when it can be determined with a reasonable accuracy

### ISSUE THREAD

**Issue by sluukkonen** [reitti/reittiopas#34]
What should the accuracy be? Maybe something like 100 meters.

**Comment by teropa** [comment]
Related comments from Visa:

Toinen
omituinen juttu oli se, että annoin sovellukselle aluksi oikeuden
käyttää sijaintiani. Vaikka sittemmin muutin lähtöpaikan eri paikaksi,
ympyrä, joka indikoi geolokaation tarkkuutta jäi edelleen näkyviin.
Ympyrä oli niin suuri, että sen toinen reuna oli Valkeakoskella ja
toinen 100 kilometriä Tallinnan eteläpuolella. Ehdotan seuraavia
parannuksia:
1. Geolokaatiosta saatu sijainti hylätään, jos se ei ole kovin tarkka
2. Lähtöpaikkakentän viereen lisätään geolokaationappula, joka on
oletuksena kytkettynä, ellei lokaatiota hylätä yllä olevin perustein.
Se myös kytkeytyy pois, jos käyttäjä muuttaa lähtöpaikkaa
manuaalisesti. Geolokaation voi näin kytkeä uudelleen päälle
halutessaan.
