### ISSUE TITLE
Indexing word-by-word

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#35]
I.e. it should find "Olutravintola Nurkka" when typing "Nurkka".

**Comment by joonas-sollasvaara** [comment]
Should this feature be so that it won't show "Olutravintola Nurkka" when you have typed just "Nurkk"?
I mean if you're trying to get for example to Malmi and you type in "mal", it can be annoying if it'll just flood you with stuff like "Ravintola Mallaskaski" etc.

**Comment by teropa** [comment]
This may be true. I think we'll need to try both approaches to see what works best.
