### ISSUE TITLE
Map styling

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#50]
The default google maps style is a bit noisy, with colors and extraneous information that grab the attention from the main point, which is the routes. 

Explore the styling features of Maps API v3 to see what can be done.

**Comment by teropa** [comment]
A much more pleasant map here (although it's highlighting different things than we probably want to, since it's mainly for driving) http://hairycow.name/commute_map/map.html#from:94703

**Comment by sluukkonen** [comment]
We should also consider using openstreetmap. There's a lot you can do with
OSM/Mapnik. It might be too much work for us, though.

On 11.9.2012, at 22.54, Tero Parviainen notifications@github.com wrote:

The default google maps style is a bit noisy, with colors and extraneous
information that grab the attention from the main point, which is the
routes.

Explore the styling features of Maps API v3 to see what can be done.

—
Reply to this email directly or view it on
GitHubhttps://github.com/reitti/reittiopas/issues/50.

**Comment by teropa** [comment]
One other alternative is Cloudmade. They provide different raster styles generated from OSM data, and some kind of tools for generating your own. Looks like it's free for free apps.

http://maps.cloudmade.com/

**Comment by teropa** [comment]
Closing after desaturating the google map a bit, which fixes my original complaint.
We can open separate issues for other possible enhancements.

**Comment by sluukkonen** [comment]
Leaving this here http://mapbox.com/tilemill/
