### ISSUE TITLE
Date picker not initialized on Firefox, Safari

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#71]
Chrome is OK, others not.

**Comment by sluukkonen** [comment]
It's because there isn't one, it just uses the HTML5 `<input type="date">` date picker. Chrome, Opera and the mobile devices have support for it.

**Comment by teropa** [comment]
Ah, right. There should be a JS fallback.

Android also doesn't have native HTML5 pickers - except for _some_ of the new 4.x models.

**Comment by teropa** [comment]
now using bootstrap-datepicker, but only as fallback
