### ISSUE TITLE
Nail the route selection / expansion

### ISSUE THREAD

**Issue by teropa** [reitti/reittiopas#80]
- Probably better _not_ to expand the first route by default.
- Then the map would be empty after the route search, before selecting one of the routes.
  - Or not, if there were separate selected / not selected and expanded / not expanded states, and we could _select_ but not _expand_ the first route. But I think we should minimize states and this is way too much.
  - This isn't an issue on small screens since the map isn't shown at this point anyway.

**Comment by sluukkonen** [comment]
If the current scrolling implementation isn't too confusing, I think it this quite well right now.

**Comment by teropa** [comment]
It's OK, but breaks scrolling on Android (at leat 2.x)
